#添加Eureka相关的配置文件
server:
  port: 8081
spring:
  application:
    name: provider             #这个是要注册到注册中心的微服务的名称

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
    instance:
      prefer-ip-address: true         #是否将当前服务的ip注册到EurekaServer